### ISSUE TITLE
[Errno 2] No such file or directory: './checkpoint/synthetic_animal/horse_multitask/model_best.pth.tar'

### ISSUE THREAD

**Issue by nightfarrow** [JitengMu/Learning-from-Synthetic-Animals#1]
Hi,

I'm on this step:

`Run the demo.ipynb to visualize predictions.`

and when I do `$ runipy demo.ipynb` I get:

```
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/synthetic_animal/horse_multitask/model_best.pth.tar'
01/08/2021 05:33:25 AM INFO: Shutdown kernel
01/08/2021 05:33:25 AM WARNING: Exiting with nonzero exit status

```

I'm not sure what to do from here. Can you please advise?

**Comment by realmoment2017** [comment]
Have you checked whether there is such a file in the directory? If not, please follow get_checkpoint.sh to download the corresponding checkpoint files.

**Comment by Learningm** [comment]
> Have you checked whether there is such a file in the directory? If not, please follow get_checkpoint.sh to download the corresponding checkpoint files.

I met the similar problem when I tried to test multi-task part. Checkpoints downloaded following get_checkpoint.sh do not have multi_task related checkpoints, I got four checkpoints of horse, including horse_ccssl, horse_finetune, horse_hourglass, horse_spaug, no multitask postfix.
Where can I download the multi_task checkpoint related?

**Comment by JitengMu** [comment]
Thanks for your interest. Sorry that I just realized that the original checkpoint is not included. But maybe training scratch is possible? I trained a new one and it's uploaded here, https://www.cs.jhu.edu/~qiuwch/animal/
