### ISSUE TITLE
Potential part indexing mistake in Tiger dataset?

### ISSUE THREAD

**Issue by wangkaihong** [JitengMu/Learning-from-Synthetic-Animals#10]
Hi!

Thanks for sharing this interesting work! I would like to double-check about a potential part indexing mistake when I browsed your data generating code and dataloaders:

![image](https://user-images.githubusercontent.com/23068166/152669231-8fc5871a-eb7f-4d88-a8ec-1cc5226a922d.png)

Would you please clarify if "2573" and "2679" are in the wrong order? Cause I found in Horse's dataloader that the order remains the same:

![image](https://user-images.githubusercontent.com/23068166/152669278-f7c579e5-032e-4d34-a397-368868db1635.png)

Thanks!

**Comment by JitengMu** [comment]
Hi, thanks for your interest in our work. The kp_18_id in the data_generation file is just for checking if there are enough key points visible and through away images with few visible key points. So the order should not matter. The CCSSL file determines what the model learns.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/61759827/152694519-cab4a715-cfaa-4918-84fd-e5feafb5ba9b.png">

**Comment by wangkaihong** [comment]
Thanks for the clarification!
