### ISSUE TITLE
pck@0.05？

### ISSUE THREAD

**Issue by YuQi9797** [JitengMu/Learning-from-Synthetic-Animals#11]
Hi!

Thanks for the remarkable work! Just wanted to check if the PCK@0.05 is actually PCK@0.5 ？
![@Q25SF@G 7Z1QN4ODI WK1D](https://user-images.githubusercontent.com/32479497/157662254-3150a51a-5197-4013-b085-82420c3da3de.png)

**Comment by realmoment2017** [comment]
Let me know if this addresses your concerns. Please check the accuracy_2animal() function, where the distances are first divided by 10 and another threshold 0.5 is then applied. So it should be PCK@0.05 rather than PCK@0.5

**Comment by JitengMu** [comment]
Let me know if this addresses your concerns. Please check the accuracy_2animal() function, where the distances are first divided by 10 and another threshold 0.5 is then applied. So it should be PCK@0.05 rather than PCK@0.5

**Comment by YuQi9797** [comment]
yeah, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月13日(星期天) 上午7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JitengMu/Learning-from-Synthetic-Animals] ***@***.***？ (Issue #11)





 
Let me know if this addresses your concerns. Please check the accuracy_2animal() function, where the distances are first divided by 10 and another threshold 0.5 is then applied. So it should be ***@***.*** rather than ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
