### ISSUE TITLE
The link "animal_data" is broken. Move it to the recycle bin? This link cannot be used because its target "path_to_images-dir" does not exist.

### ISSUE THREAD

**Issue by zxl12128728** [JitengMu/Learning-from-Synthetic-Animals#13]
The link "animal_data" is broken. Move it to the recycle bin? This link cannot be used because its target "path_to_images-dir" does not exist.

**Comment by JitengMu** [comment]
Thanks, but I am not sure which link you are referring to. Maybe you can copy the link here?

**Comment by zxl12128728** [comment]
ln -s PATH_TO_IMAGES_DIR ./animal_data.I cannot create a soft connection

**Comment by JitengMu** [comment]
Please replace PATH_TO_IMAGES_DIR with the actual file location. It might also be helpful to check " ln -s " command for a better understanding.

**Comment by zxl12128728** [comment]
Thanks!


赵雪莲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JitengMu/Learning-from-Synthetic-Animals"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JitengMu/Learning-from-Synthetic-Animals] The link "animal_data" is broken. Move it to the recycle bin? This link cannot be used because its target "path_to_images-dir" does not exist. (Issue #13)





 
Please replace PATH_TO_IMAGES_DIR with the actual file location. It might also be helpful to check " ln -s " command for a better understanding.
