### ISSUE TITLE
How to get the keypoints index for another kind of animal? 

### ISSUE THREAD

**Issue by ChiyuanFeng** [JitengMu/Learning-from-Synthetic-Animals#2]
Is there anyway to get the keypoints index for another kind of animal?  For example, 'domestic_pig'? Any information will be appreciated.

Best,
Will

**Comment by realmoment2017** [comment]
Hi, I think first you need to get the asset mentioned in the paper. You may use Unreal Engine to open these .uasset files and export them to mesh files (e.g., FBX). Then you can use any renderer to check mesh vertices IDs.

**Comment by ChiyuanFeng** [comment]
> Hi, I think first you need to get the asset mentioned in the paper. You may use Unreal Engine to open these .uasset files and export them to mesh files (e.g., FBX). Then you can use any renderer to check mesh vertices IDs.

Thank you for you kindly reply.

**Comment by ChiyuanFeng** [comment]
> Hi, I think first you need to get the asset mentioned in the paper. You may use Unreal Engine to open these .uasset files and export them to mesh files (e.g., FBX). Then you can use any renderer to check mesh vertices IDs.

Hello,

I found it's a real pain to check for the index one by one for the key-points, not to mention the part segmentation.

**Comment by ChiyuanFeng** [comment]
> Hi, I think first you need to get the asset mentioned in the paper. You may use Unreal Engine to open these .uasset files and export them to mesh files (e.g., FBX). Then you can use any renderer to check mesh vertices IDs.

I finished this, thank you
