### ISSUE TITLE
multitask result is different from paper

### ISSUE THREAD

**Issue by Learningm** [JitengMu/Learning-from-Synthetic-Animals#3]
Hi, this work is pretty cool and I came across some questions when I use this repo. I did not find checkpoint with multitask postfix following the get_checkpoint.sh scripts, so I train from scratch using sample command in train.md. 

#### Example 4: Train on synthetic animals (multi-task setting) and evaluate on real animals(TigDog) 

Training:

```
CUDA_VISIBLE_DEVICES=0 python train/train_multitask.py --dataset synthetic_animal_sp_multitask -a hg_multitask --stacks 4 --blocks 1 --image-path ./animal_data/ --checkpoint ./checkpoint/synthetic_animal/horse/horse_multitask --animal horse
```

Evaluation:

```
CUDA_VISIBLE_DEVICES=0 python ./evaluation/test.py --dataset1 synthetic_animal_sp_multitask --dataset2 real_animal_sp --arch hg_multitask --resume ./checkpoint/synthetic_animal/horse/horse_multitask/model_best.pth.tar --evaluate --animal horse
```

I get 60.03 acc when I evaluate on the real animal images, which should be 62.25 mentioned in paper Table.3.

Could you help me figure out which part matters? Thank you !

**Comment by JitengMu** [comment]
Thanks for your interest. Maybe you can give it another try and see what the results are? How about other categories? Are they consistently lower? From what I understand, due to the uncertainty of generalization, I think certain amount of variances is expected.

**Comment by JitengMu** [comment]
Hello, I'm going to close the issue as I did not see further responses. Feel free to re-open the issue if the problem still exists.
