### ISSUE TITLE
The model I trained from scratch is lower than the model downloaded by checkpoint. Why is it?

### ISSUE THREAD

**Issue by wenwenzhanghaha123wonder** [JitengMu/Learning-from-Synthetic-Animals#6]
Hi！
The model I trained from scratch is lower than the model downloaded by checkpoint. Why is it?

**Comment by realmoment2017** [comment]
Thanks for your interest. Maybe I can explain better if you may provide more details, e.g., which exp and what the performance is?

**Comment by JitengMu** [comment]
Maybe I can explain better if you may provide more details, e.g., which setting and what numbers you got?

**Comment by JitengMu** [comment]
Hello, I'm going to close the issue as I did not see further responses. Feel free to re-open the issue if the problem still exists.
