### ISSUE TITLE
结果评价指标的代码问题

### ISSUE THREAD

**Issue by YuQi9797** [JitengMu/Learning-from-Synthetic-Animals#9]
您好，请问
https://github.com/JitengMu/Learning-from-Synthetic-Animals/blob/master/evaluation/test.py#L228-L234
`acces.avg` 是否就是论文实验结果中的 Mean呢？   ，`    print(list(pck_score))`  即为每个部位的pck值？

**Comment by JitengMu** [comment]
是的

**Comment by YuQi9797** [comment]
好的，谢谢您！
